name: Cypress Scheduled Run

on:
  schedule:
    - cron: '15 12 * * *'  # Daily at 5:45 PM IST (12:15 UTC)
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: Install Dependencies
        run: npm ci

      - name: Clean old reports
        run: npm run clean:reports

      - name: Run Cypress Tests (Record + Mochawesome)
        run: npm run cy:run

      - name: Debug - List Report Files
        run: |
          echo "Listing report directory"
          ls -R cypress/reports

      - name: Merge Mochawesome JSON Reports
        run: npm run mocha:merge

      - name: Generate Final HTML Report
        run: npm run mocha:report

      - name: Generate Regression Summary
        run: npm run summary

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-html-report
          path: cypress/reports/final-report.html